//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.HiddenField hfContactID;
		
		protected System.Web.UI.WebControls.Label Label1;
		
		protected System.Web.UI.WebControls.TextBox txtName;
		
		protected System.Web.UI.WebControls.Label Label2;
		
		protected System.Web.UI.WebControls.TextBox txtDate;
		
		protected System.Web.UI.WebControls.Label Label3;
		
		protected System.Web.UI.WebControls.TextBox txtDesignation;
		
		protected System.Web.UI.WebControls.Label Label4;
		
		protected System.Web.UI.WebControls.ListBox lstSkills;
		
		protected System.Web.UI.WebControls.Button btnSave;
		
		protected System.Web.UI.WebControls.Button btnDelete;
		
		protected System.Web.UI.WebControls.Button btnClear;
		
		protected System.Web.UI.WebControls.Label lblSuccessMessage;
		
		protected System.Web.UI.WebControls.Label lblErrorMessage;
		
		protected System.Web.UI.WebControls.GridView gvContact;
		
		protected System.Web.UI.WebControls.LinkButton lnkView;
	}
}
